- hosts: localhost
  # become_user: "{{ lookup('env', 'USER') }}"
  become: true
  # # TODO: ADD VAULT PASSWORD
  # vars_prompt:
  #   - name: "vault_password"
  #     prompt: "Enter Vault Pasword"
  #     private: yes
  vars:
    ansible_ssh_private_key_file: $HOME/.ssh/id_ed25519

  pre_tasks:
    - name: Update brew and upgrade all packages
      shell: brew update && brew upgrade && brew upgrade --cask && brew cleanup
      tags:
        - install
      become: false
      when: ansible_os_family == "Darwin"

    - name: Update system
      community.general.pacman:
        update_cache: true
        upgrade: true
      tag:
        - install
      when: ansible_os_family == "Archlinux"

  tasks:
    - block:
      - name: Core Dependencies
        ansible.builtin.import_tasks: arch/tasks/core-setup.yml
      
      - name: Zsh Setup
        ansible.builtin.import_tasks: arch/tasks/zsh.yml 

      become_user: "{{ lookup('env', 'USER') }}"
      become: true
      when: ansible_os_family == "Archlinux"

    # - block:
    #   - name: Core Dependencies
    #     ansible.builtin.import_tasks: iOS/tasks/gcore-setup.yml
    #
    #   - name: Zsh Setup
    #     ansible.builtin.import_tasks: iOS/tasks/gzsh.yml
    #
    #   - name: Dotfiles Setup 
    #     ansible.builtin.import_tasks: iOS/tasks/gdotfiles.yml
    #
    #   - name: Tmux Setup 
    #     ansible.builtin.import_tasks: iOS/tasks/gtmux.yml
    #
    #   - name: Neovim Setup
    #     ansible.builtin.import_tasks: iOS/tasks/gnvim.yml
    #   become_user: "{{ lookup('env', 'USER') }}"
    #   when: ansible_os_family == "Darwin"
