- name: Install System Packages
  apt: name={{item}}
  with_items:
    - build-essential
    - sudo
    - man
    - git
    - curl
    - vim
    - rsync
    - fzf
    - tldr
    - tree
  tags:
    - install
    - core
- name: Create personal folder
  shell: mkdir $HOME/work && mkdir $HOME/projects && mkdir $HOME/personal
  tags:
    - create
    - personal
