- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
- name: Coping dotfiles folder
  shell: rsync -r ~/.chaConfig/dotfiles/ $HOME/.dotfiles
  tags:
    - install
    - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && rm $HOME/.zshrc && ./install
  tags:
    - install
    - dotfiles
