- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
- name: Coping dotfiles folder
  shell: rsync -r ~/.chaCon/dotfiles/ $HOME/.dotfiles
  tags:
    - install
    - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu
  tags:
    - install
    - dotfiles
