- name: Install System Packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - curl
    - vim
    - tree
    - ssh
    - sshs
  tags:
    - install
    - core
- name: Create personal folder
  shell: mkdir -p $HOME/workspace/work $HOME/workspace/personal $HOME/workspace/github.com/chaCon $HOME/workspace/projects
  tags:
    - personal
