- name: Installing stow
  homebrew: name=stow
  tags:
    - install
    - dotfiles
- name: Check If .zshrc Exist
  stat:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
  register: zshrc_path
- name: Delete .zshrc
  shell: rm $HOME/.zshrc
  tags:
    - install
    - dotfiles
  when: zshrc_path.stat.exists
- name: Stow dotfiles
  shell: $HOME/.chaConfig/iOS/dotfiles/install
  tags:
    - install
    - dotfiles
