- name: Installing stow
  homebrew: name=stow
  tags:
    - install
    - dotfiles
# FIX: HACER QUE FUNCIONE LO DE DAWRIN
- name: Delete .zshrc
  shell: rm $HOME/.zshrc
  tags:
    - install
    - dotfiles
- name: Stow dotfiles
  shell: $HOME/.chaConfing/iOS/dotfiles/install
  tags:
    - install
    - dotfiles
