- name: Install ZSH and Dependencies
  homebrew: 
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
    - fzf
    - fd
    - bat
    - git-delta
    - eza
    - tldr
    - zoxide
  tags:
    - install
    - zsh
- name: Check If Oh My Zsh Exist
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_zsh_path
- block:
    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      tags:
        - install
        - zsh
    - name: Install Autosuggestions
      git: 
        repo: https://github.com/zsh-users/zsh-autosuggestions 
        dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        force: true
      tags:
        - install
        - zsh
    - name: Install Syntax Highlighting
      git: 
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git 
        dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        force: true
      tags:
        - install
        - zsh
  when: not oh_my_zsh_path.stat.exists
- name: Install p10k
  shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
  tags:
    - install
    - p10k
- name: Install Git fzf 
  git:
    repo: 'https://github.com/junegunn/fzf-git.sh.git'
    dest: "{{ lookup('env','HOME') }}/.fzf-git.sh"
    force: true
  tags:
    - install
    - zsh
