- name: Install System Packages
  community.general.pacman:
    name:
      - mlocate
      - xorg
      - go
      - git
      - base-devel
      - htop
      - neofetch
    state: present
  tags:
    - core
    - install

- name: Install yay
  shell: pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
  become: true
  tags:
    - core
    - install
    - yay

- name: Install picom
  shell: yay -S picom

- name: Create personal folder
  shell: mkdir $HOME/work && mkdir $HOME/projects && mkdir $HOME/personal
  tags:
    - create
    - personal
