- name: Nvim prerequisites
  shell: brew install --HEAD neovim
  tags:
    - install
    - nvim

# FIX: AGREGAR LAS COSAS QUE SE NECESITAN, ENTRE ELLAS
#  - brew install luajit
- name: Nvim Config
  shell: |
    mkdir -p $HOME/.config
    git clone https://github.com/Chacon-tu-drema/chaCon.nvim $HOME/.config/nvim
  tags:
    - config
    - nvim
- name: Nvim Neceseties
  shell: |
    xcode-select --install
    brew install ripgrep fd
    brew install luajit
