- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
- name: Check If .zshrc Exist
  stat:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
  register: zshrc_path
- name: Delete .zshrc
  shell: rm $HOME/.zshrc
  tags:
    - install
    - dotfiles
  when: zshrc_path.stat.exists
- name: Stow dotfiles
  # FIX: Agregar {{}} configuracion y pasar la configuracion como parametro de tag
  shell: $HOME/.chaConfig/ubuntu_server/dotfiles/install
  tags:
    - install
    - dotfiles
