- name: Nvim prerequisites
  apt: name={{ item }}
  with_items:
    - ninja-build
    - gettext
    - cmake
    - unzip
    - curl
  tags:
    - install
    - nvim
- name: Cloning Nvim
  shell: git clone https://github.com/neovim/neovim $HOME/.local/bin/nvim
  tags:
    - install
    - nvim
- name: Building Nvim
  shell: |
    cd $HOME/.local/bin/nvim
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    git checkout stable
    make install
  tags:
    - install
    - nvim
- name: Nvim Config
  shell: |
    mkdir -p $HOME/.config
    git clone https://github.com/Chacon-tu-drema/chaCon.nvim $HOME/.config/nvim
  tags:
    - config
    - nvim
