- name: Installing Tmux
  apt: name=tmux
  tags:
    - install
    - tmux
- name: Plugging Tmux TPM
  shell: mkdir $HOME/.tmux && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  tags:
    - install
    - tmux
