- name: Nvim prerequisites
  apt: name={{ item }}
  with_items:
    - neovim 
    - python-pynvim
  tags:
    - install
    - nvim
- name: Nvim Config
  shell: |
    mkdir -p $HOME/.config
    git clone https://github.com/Chacon-tu-drema/chaCon.nvim $HOME/.config/nvim
  tags:
    - config
    - nvim
