- name: Install ZSH Tools
  pacman: name={{ item }}
  with_items:
    - fzf
    - fd
    - bat
    - eza
    - zoxide

- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - install
    - zsh

- name: Install zsh-autosuggestions
  shell: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  tags:
    - install
    - zsh

- name: Install zsh-syntax-highlighting
  shell: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
  tags:
    - install
    - zsh
- name: Install p10k
  shell: yay -S --noconfirm zsh-theme-powerlevel10k-git
  tags:
    - p10k
    - install
- name: Delete .zshrc
  shell: rm ~/.zshrc
- name: Install fzf Git
  shell: git clone https://github.com/junegunn/fzf-git.sh.git $HOME/.fzf-git.sh
