- name: Set up chaCon
  hosts: localhost
  become: true
  vars:
    ansible_ssh_private_key_file: $HOME/.ssh/id_ed25519
  # FIX: ansible_os_family

  tasks:
    - block:
        - name: Core Dependencies
          ansible.builtin.import_tasks: arch/tasks/core-setup.yml
        - name: Zsh Setup
          ansible.builtin.import_tasks: arch/tasks/zsh.yml
        - name: Alacritty Setup
          ansible.builtin.import_tasks: arch/tasks/alacritty.yml
        - name: i3 Setup
          ansible.builtin.import_tasks: arch/tasks/i3.yml
        - name: Tmux Setup
          ansible.builtin.import_tasks: arch/tasks/tmux.yml
        - name: Dotfiles Setup
          ansible.builtin.import_tasks: arch/tasks/dotfiles.yml
        - name: Neovim Setup
          ansible.builtin.import_tasks: arch/tasks/nvim.yml
      when: ansible_facts['os_family'] == "Archlinux"
    - block:
        - name: Core Dependencies
          ansible.builtin.import_tasks: iOS/tasks/core-setup.yml
        - name: Zsh Setup
          ansible.builtin.import_tasks: iOS/tasks/zsh.yml
        - name: Dotfiles Setup
          ansible.builtin.import_tasks: iOS/tasks/dotfiles.yml
        - name: Tmux Setup
          ansible.builtin.import_tasks: iOS/tasks/tmux.yml
        - name: Neovim Setup
          ansible.builtin.import_tasks: iOS/tasks/nvim.yml
      become_user: "{{ lookup('env', 'USER') }}"
      when: ansible_facts['os_family'] == "Darwin"
